# Generated by Django 5.0.6 on 2024-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNo', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
